# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbackend.proto\x12\x07\x62\x61\x63kend\"A\n GetRequestedFlightsByUserRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"\x9d\x01\n\x19\x46lightRequestedByUserItem\x12\x1c\n\x14requested_by_user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x18\n\x10\x66rom_destination\x18\x03 \x01(\t\x12\x11\n\tfrom_date\x18\x04 \x01(\t\x12\x16\n\x0eto_destination\x18\x05 \x01(\t\x12\x0f\n\x07to_date\x18\x06 \x01(\t\"V\n!GetRequestedFlightsByUserResponse\x12\x31\n\x05items\x18\x01 \x03(\x0b\x32\".backend.FlightRequestedByUserItem\"c\n$SendProcessedFlightsByCrawlerRequest\x12;\n\x0fprocessed_items\x18\x01 \x03(\x0b\x32\".backend.FlightRequestedByUserItem\"I\n%SendProcessedFlightsByCrawlerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x84\x02\n\rFlightService\x12s\n\x1aGetRequestedFlightsByUsers\x12).backend.GetRequestedFlightsByUserRequest\x1a*.backend.GetRequestedFlightsByUserResponse\x12~\n\x1dSendProcessedFlightsByCrawler\x12-.backend.SendProcessedFlightsByCrawlerRequest\x1a..backend.SendProcessedFlightsByCrawlerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUESTEDFLIGHTSBYUSERREQUEST']._serialized_start=26
  _globals['_GETREQUESTEDFLIGHTSBYUSERREQUEST']._serialized_end=91
  _globals['_FLIGHTREQUESTEDBYUSERITEM']._serialized_start=94
  _globals['_FLIGHTREQUESTEDBYUSERITEM']._serialized_end=251
  _globals['_GETREQUESTEDFLIGHTSBYUSERRESPONSE']._serialized_start=253
  _globals['_GETREQUESTEDFLIGHTSBYUSERRESPONSE']._serialized_end=339
  _globals['_SENDPROCESSEDFLIGHTSBYCRAWLERREQUEST']._serialized_start=341
  _globals['_SENDPROCESSEDFLIGHTSBYCRAWLERREQUEST']._serialized_end=440
  _globals['_SENDPROCESSEDFLIGHTSBYCRAWLERRESPONSE']._serialized_start=442
  _globals['_SENDPROCESSEDFLIGHTSBYCRAWLERRESPONSE']._serialized_end=515
  _globals['_FLIGHTSERVICE']._serialized_start=518
  _globals['_FLIGHTSERVICE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
