# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scraper.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scraper.proto',
  package='scraper',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rscraper.proto\x12\x07scraper\"\xb8\x01\n\x19\x46lightRequestedByUserItem\x12\x1c\n\x14requested_by_user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x18\n\x10\x66rom_destination\x18\x03 \x01(\t\x12\x11\n\tfrom_date\x18\x04 \x01(\t\x12\x16\n\x0eto_destination\x18\x05 \x01(\t\x12\x0f\n\x07to_date\x18\x06 \x01(\t\x12\x19\n\x11is_foreign_flight\x18\x07 \x01(\x08\"p\n!GetRequestedFlightsByUserResponse\x12\x15\n\rprovider_name\x18\x01 \x01(\t\x12\x34\n\x08requests\x18\x02 \x03(\x0b\x32\".scraper.FlightRequestedByUserItem\"\x9f\x02\n\x0f\x46lightProcessed\x12\x15\n\rprovider_name\x18\x01 \x01(\t\x12\x0e\n\x06origin\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x1b\n\x13\x64\x65parture_date_time\x18\x04 \x01(\t\x12\x19\n\x11\x61rrival_date_time\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x64ult_price\x18\x06 \x01(\x03\x12\x17\n\x0f\x61irline_name_fa\x18\x07 \x01(\t\x12\x17\n\x0f\x61irline_name_en\x18\x08 \x01(\t\x12\x15\n\rflight_number\x18\t \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\n \x01(\x05\x12\r\n\x05rules\x18\x0b \x01(\t\x12\x19\n\x11is_foreign_flight\x18\x0c \x01(\x08\"I\n\x1c\x46lightProcessedByUserReqeust\x12)\n\x07\x66lights\x18\x01 \x03(\x0b\x32\x18.scraper.FlightProcessed2s\n\x0eScraperService\x12\x61\n\x0cTakeRequests\x12*.scraper.GetRequestedFlightsByUserResponse\x1a%.scraper.FlightProcessedByUserReqeustb\x06proto3'
)




_FLIGHTREQUESTEDBYUSERITEM = _descriptor.Descriptor(
  name='FlightRequestedByUserItem',
  full_name='scraper.FlightRequestedByUserItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requested_by_user_id', full_name='scraper.FlightRequestedByUserItem.requested_by_user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='scraper.FlightRequestedByUserItem.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_destination', full_name='scraper.FlightRequestedByUserItem.from_destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_date', full_name='scraper.FlightRequestedByUserItem.from_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_destination', full_name='scraper.FlightRequestedByUserItem.to_destination', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_date', full_name='scraper.FlightRequestedByUserItem.to_date', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_foreign_flight', full_name='scraper.FlightRequestedByUserItem.is_foreign_flight', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=211,
)


_GETREQUESTEDFLIGHTSBYUSERRESPONSE = _descriptor.Descriptor(
  name='GetRequestedFlightsByUserResponse',
  full_name='scraper.GetRequestedFlightsByUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider_name', full_name='scraper.GetRequestedFlightsByUserResponse.provider_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requests', full_name='scraper.GetRequestedFlightsByUserResponse.requests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=325,
)


_FLIGHTPROCESSED = _descriptor.Descriptor(
  name='FlightProcessed',
  full_name='scraper.FlightProcessed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider_name', full_name='scraper.FlightProcessed.provider_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='origin', full_name='scraper.FlightProcessed.origin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destination', full_name='scraper.FlightProcessed.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='departure_date_time', full_name='scraper.FlightProcessed.departure_date_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arrival_date_time', full_name='scraper.FlightProcessed.arrival_date_time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adult_price', full_name='scraper.FlightProcessed.adult_price', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='airline_name_fa', full_name='scraper.FlightProcessed.airline_name_fa', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='airline_name_en', full_name='scraper.FlightProcessed.airline_name_en', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flight_number', full_name='scraper.FlightProcessed.flight_number', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='scraper.FlightProcessed.capacity', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rules', full_name='scraper.FlightProcessed.rules', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_foreign_flight', full_name='scraper.FlightProcessed.is_foreign_flight', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=615,
)


_FLIGHTPROCESSEDBYUSERREQEUST = _descriptor.Descriptor(
  name='FlightProcessedByUserReqeust',
  full_name='scraper.FlightProcessedByUserReqeust',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flights', full_name='scraper.FlightProcessedByUserReqeust.flights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=690,
)

_GETREQUESTEDFLIGHTSBYUSERRESPONSE.fields_by_name['requests'].message_type = _FLIGHTREQUESTEDBYUSERITEM
_FLIGHTPROCESSEDBYUSERREQEUST.fields_by_name['flights'].message_type = _FLIGHTPROCESSED
DESCRIPTOR.message_types_by_name['FlightRequestedByUserItem'] = _FLIGHTREQUESTEDBYUSERITEM
DESCRIPTOR.message_types_by_name['GetRequestedFlightsByUserResponse'] = _GETREQUESTEDFLIGHTSBYUSERRESPONSE
DESCRIPTOR.message_types_by_name['FlightProcessed'] = _FLIGHTPROCESSED
DESCRIPTOR.message_types_by_name['FlightProcessedByUserReqeust'] = _FLIGHTPROCESSEDBYUSERREQEUST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightRequestedByUserItem = _reflection.GeneratedProtocolMessageType('FlightRequestedByUserItem', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTREQUESTEDBYUSERITEM,
  '__module__' : 'scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.FlightRequestedByUserItem)
  })
_sym_db.RegisterMessage(FlightRequestedByUserItem)

GetRequestedFlightsByUserResponse = _reflection.GeneratedProtocolMessageType('GetRequestedFlightsByUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUESTEDFLIGHTSBYUSERRESPONSE,
  '__module__' : 'scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.GetRequestedFlightsByUserResponse)
  })
_sym_db.RegisterMessage(GetRequestedFlightsByUserResponse)

FlightProcessed = _reflection.GeneratedProtocolMessageType('FlightProcessed', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTPROCESSED,
  '__module__' : 'scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.FlightProcessed)
  })
_sym_db.RegisterMessage(FlightProcessed)

FlightProcessedByUserReqeust = _reflection.GeneratedProtocolMessageType('FlightProcessedByUserReqeust', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTPROCESSEDBYUSERREQEUST,
  '__module__' : 'scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.FlightProcessedByUserReqeust)
  })
_sym_db.RegisterMessage(FlightProcessedByUserReqeust)



_SCRAPERSERVICE = _descriptor.ServiceDescriptor(
  name='ScraperService',
  full_name='scraper.ScraperService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=692,
  serialized_end=807,
  methods=[
  _descriptor.MethodDescriptor(
    name='TakeRequests',
    full_name='scraper.ScraperService.TakeRequests',
    index=0,
    containing_service=None,
    input_type=_GETREQUESTEDFLIGHTSBYUSERRESPONSE,
    output_type=_FLIGHTPROCESSEDBYUSERREQEUST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCRAPERSERVICE)

DESCRIPTOR.services_by_name['ScraperService'] = _SCRAPERSERVICE

# @@protoc_insertion_point(module_scope)
